/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agentvalorant;

import agentvalorant.data.Admin;
import agentvalorant.data.Agent;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo - GK
 */
public class AddAgent extends javax.swing.JFrame {

    /**
     * Creates new form AddAgent
     */
    private Connection con;
    private Statement stat;
    private ResultSet res;

    public AddAgent() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void cls() {
        txtnama.setText("");
        cbrole.setSelectedItem("Duelist");
        txtskill.setText("");
        txtutil.setText("");
        txtPrice.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnama = new javax.swing.JTextField();
        cbrole = new javax.swing.JComboBox<>();
        txtskill = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtutil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("AddAgent"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        txtnama.setBackground(new java.awt.Color(102, 0, 0));
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setText(" Nama Agent");
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });
        jPanel1.add(txtnama);
        txtnama.setBounds(100, 70, 202, 30);

        cbrole.setBackground(new java.awt.Color(102, 0, 0));
        cbrole.setForeground(new java.awt.Color(255, 255, 255));
        cbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Duelist", "Controller", "Sentinel", "Initiator" }));
        cbrole.setName(""); // NOI18N
        jPanel1.add(cbrole);
        cbrole.setBounds(100, 110, 202, 30);

        txtskill.setBackground(new java.awt.Color(102, 0, 0));
        txtskill.setForeground(new java.awt.Color(255, 255, 255));
        txtskill.setText(" Skill Agent");
        txtskill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtskillFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtskillFocusLost(evt);
            }
        });
        jPanel1.add(txtskill);
        txtskill.setBounds(100, 150, 202, 30);

        txtPrice.setBackground(new java.awt.Color(102, 0, 0));
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setText("Price Agent");
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        jPanel1.add(txtPrice);
        txtPrice.setBounds(100, 230, 202, 30);

        btnsimpan.setBackground(new java.awt.Color(255, 255, 204));
        btnsimpan.setForeground(new java.awt.Color(102, 0, 0));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan);
        btnsimpan.setBounds(100, 270, 202, 30);

        btnback.setBackground(new java.awt.Color(102, 0, 0));
        btnback.setForeground(new java.awt.Color(255, 255, 204));
        btnback.setText("Back");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(10, 310, 40, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Data Agent");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 170, 30);

        txtutil.setBackground(new java.awt.Color(102, 0, 0));
        txtutil.setForeground(new java.awt.Color(255, 255, 255));
        txtutil.setText(" Utility Agent");
        txtutil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtutilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtutilFocusLost(evt);
            }
        });
        jPanel1.add(txtutil);
        txtutil.setBounds(100, 190, 202, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        InterfaceMenu InterfaceMenu = new InterfaceMenu();
        InterfaceMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        Admin adm = new Admin("", "", "");
        String nm, role, skill, util, price;
        nm = txtnama.getText();
        role = cbrole.getSelectedItem().toString();
        skill = txtskill.getText();
        util = txtutil.getText();
        price = txtPrice.getText();

        try {
            if (adm.createAgent(new Agent(-1, nm, role, skill, util, price))) {
                JOptionPane.showMessageDialog(this, "Berhasil Menambahkan Agent!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                InterfaceMenu InterfaceMenu = new InterfaceMenu();
                InterfaceMenu.setVisible(true);
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        String nm = txtnama.getText();
        if (nm.equals("Nama Agent")) {
            txtnama.setText("");
        }
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        String nm = txtnama.getText();
        if (nm.equals("") || nm.equals("Nama Agent")) {
            txtnama.setText("Nama Agent");
        }
    }//GEN-LAST:event_txtnamaFocusLost

    private void txtskillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtskillFocusGained
        String skill = txtskill.getText();
        if (skill.equals("Skill Agent")) {
            txtskill.setText("");
        }
    }//GEN-LAST:event_txtskillFocusGained

    private void txtskillFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtskillFocusLost
        String skill = txtskill.getText();
        if (skill.equals("") || skill.equals("Skill Agent")) {
            txtskill.setText("Skill Agent");
        }
    }//GEN-LAST:event_txtskillFocusLost

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        String price = txtPrice.getText();
        if (price.equals("Price Agent")) {
            txtPrice.setText("");
        }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        String price = txtPrice.getText();
        if (price.equals("") || price.equals("Price Agent")) {
            txtPrice.setText("Price Agent");
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtutilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtutilFocusGained
        String util = txtutil.getText();
        if (util.equals("Utility Agent")) {
            txtPrice.setText("");
        }
    }//GEN-LAST:event_txtutilFocusGained

    private void txtutilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtutilFocusLost
        String util = txtutil.getText();
        if (util.equals("") || util.equals("Utility Agent")) {
            txtutil.setText("Utility Agent");
        }    }//GEN-LAST:event_txtutilFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbrole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtskill;
    private javax.swing.JTextField txtutil;
    // End of variables declaration//GEN-END:variables
}
