/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agentvalorant;

import agentvalorant.data.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo - GK
 */
public class InterfaceRegister extends javax.swing.JFrame {
    User u = new User(-1, "p", "p", "p");
    /**
     * Creates new form InterfaceRegister
     */
    public InterfaceRegister() {
        initComponents();
        setSize(450, 430);
        setLocationRelativeTo(null); 
        setResizable(false); 
    }

    private void cls() {
        txtnama.setText("");
        txtusername.setText("");
        txtpassword.setText("");
        txtkpassword.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showkpass = new javax.swing.JCheckBox();
        txtpassword = new javax.swing.JPasswordField();
        txtkpassword = new javax.swing.JPasswordField();
        txtnama = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(452, 375));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        showkpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showkpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showkpassActionPerformed(evt);
            }
        });
        jPanel1.add(showkpass);
        showkpass.setBounds(340, 220, 20, 19);

        txtpassword.setBackground(new java.awt.Color(102, 0, 0));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setText("Password");
        txtpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtpassword);
        txtpassword.setBounds(100, 170, 230, 30);

        txtkpassword.setBackground(new java.awt.Color(102, 0, 0));
        txtkpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtkpassword.setText("Password");
        txtkpassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtkpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkpasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtkpassword);
        txtkpassword.setBounds(100, 210, 230, 30);

        txtnama.setBackground(new java.awt.Color(102, 0, 0));
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setText("Nama Lengkap");
        txtnama.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtnama.setPreferredSize(new java.awt.Dimension(64, 20));
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });
        jPanel1.add(txtnama);
        txtnama.setBounds(100, 130, 230, 30);

        txtusername.setBackground(new java.awt.Color(102, 0, 0));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("Username");
        txtusername.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(100, 90, 230, 30);

        btnregister.setBackground(new java.awt.Color(255, 255, 204));
        btnregister.setForeground(new java.awt.Color(102, 0, 0));
        btnregister.setText("Register");
        btnregister.setPreferredSize(new java.awt.Dimension(64, 20));
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister);
        btnregister.setBounds(100, 270, 230, 30);

        btnback.setBackground(new java.awt.Color(102, 0, 0));
        btnback.setForeground(new java.awt.Color(255, 255, 204));
        btnback.setText("Back");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(10, 340, 40, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Register");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 50, 70, 20);

        showpass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass);
        showpass.setBounds(340, 180, 20, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        InterfaceLogin IL = new InterfaceLogin();
        IL.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        
        String usn, nm;
        char[] pw, kpw;
        boolean adm = false;

        usn = txtusername.getText();
        pw = txtpassword.getPassword();
        kpw = txtkpassword.getPassword();
        nm = txtnama.getText();

        if (!usn.isEmpty() && pw.length != 0 && kpw.length != 0) {

            if (Arrays.equals(pw, kpw)) {

                try {
//                    if (u.register(new User(-1, usn, new String(pw), nm), false)) {
                    if (u.register(usn, new String(pw), nm, false)) {
                        JOptionPane.showMessageDialog(this, "Berhasil Melakukan Regist!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                        InterfaceLogin IL = new InterfaceLogin();
                        IL.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Username is not available", "SQL Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password Tidak Sama!", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Harap Inputkan Semua Data!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if (showpass.isSelected()) {
            txtpassword.setEchoChar((char)0);
        }
        else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void showkpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showkpassActionPerformed
        if (showkpass.isSelected()) {
            txtkpassword.setEchoChar((char)0);
        }
        else {
            txtkpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showkpassActionPerformed

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        String usn = txtusername.getText();
        if (usn.equals("Username")){
            txtusername.setText("");
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        String usn = txtusername.getText();
        if (usn.equals("")||usn.equals("Username")){
            txtusername.setText("Username");
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        String nm = txtnama.getText();
        if (nm.equals("Nama Lengkap")){
            txtnama.setText("");
        }
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        String nm = txtnama.getText();
        if (nm.equals("")||nm.equals("Nama Lengkap")){
            txtnama.setText("Nama Lengkap");
        }
    }//GEN-LAST:event_txtnamaFocusLost

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        String pass = txtpassword.getText();
        if (pass.equals("Password")){
            txtpassword.setText("");
        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        String pass = txtpassword.getText();
        if (pass.equals("")||pass.equals("Password")){
            txtpassword.setText("Password");
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtkpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkpasswordFocusGained
        String kpass = txtkpassword.getText();
        if (kpass.equals("Password")){
            txtkpassword.setText("");
        }
    }//GEN-LAST:event_txtkpasswordFocusGained

    private void txtkpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkpasswordFocusLost
        String kpass = txtkpassword.getText();
        if (kpass.equals("")||kpass.equals("Password")){
            txtkpassword.setText("Password");
        }
    }//GEN-LAST:event_txtkpasswordFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox showkpass;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JPasswordField txtkpassword;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
